### ISSUE TITLE
"5. Sell the item" does not work

### ISSUE THREAD

**Issue by takanakahiko** [gaiax/fLibra#1]
> Being on https://flibra.gaiax-blockchain.com/myPage/ no any form upon clicking on "Sell" button on the seller side browser even user was successfully registered before (Chromium 78.0.3904.108).

> Ouch, form appeared after page refresh.

Rebuilt repository for security reasons.
This issue was posted to an old repository by @vitali2y.
I reprinted this issue on behalf of him.
Thank you for reporting.

**Comment by Yosuke-Aramaki** [comment]
@vitali2y

Thank you for your issue request.
I've fixed the issue, so you can click "sell button" right after register user info without refreshing the page.

Thank you.
